            var quoteArray = [
"Forums powered by 20 cent pieces",
"Forums powered by the souls of the damned",
"Forums powered by a zx speccy",
"Forums powered by 240v mains electricity",
"Forums powered by 42",
"Forums powered by a fat guy on a bike",
"Forums powered by a glitch in the Matrix",
"Forums powered by a good idea at the time",
"Forums powered by a little man in a box",
"Forums powered by a series of mirrors",
"Forums powered by a talking horse",
"Forums powered by a three-eyed fish",
"Forums powered by alkaline batteries",
"Forums powered by an Atari 800",
"Forums powered by AOL CD-ROMs",
"Forums powered by ARP packets",
"Forums powered by bad puns",
"Forums powered by bottled human farts",
"Forums powered by butterfly sneezes ",
"Forums powered by candy!",
"Forums powered by charmed quarks",
"Forums powered by Chicken McNuggets",
"Forums powered by chinese whispers",
"Forums powered by closed captioning",
"Forums powered by cold air",
"Forums powered by Commodore 64",
"Forums powered by Commodore VIC20",
"Forums powered by cynicism",
"Forums powered by Darwin Award winners",
"Forums powered by DOS 6.22",
"Forums powered by effervescence",
"Forums powered by eight cyan geese",
"Forums powered by eight sweet midgets",
"Forums powered by eight ugly elves",
"Forums powered by eighteen dumb batteries",
"Forums powered by eighteen penguins on bicycles",
"Forums powered by eighty blue rubber ban",
"Forums powered by eighty nine grey butterflies",
"Forums powered by eighty nine orange midgets",
"Forums powered by eighty nine sweet dogs",
"Forums powered by eighty one cute cheesees",
"Forums powered by eighty one white penguins",
"Forums powered by eighty six black elves",
"Forums powered by eighty six green CD-ROMs",
"Forums powered by eighty two joyful hamsters",
"Forums powered by eighty white moons",
"Forums powered by electromagnetic cheese",
"Forums powered by elves with guns",
"Forums powered by the Emergency Medical Hologram",
"Forums powered by fifteen silly butterflies",
"Forums powered by fifty blue midgets",
"Forums powered by fifty one cute chickens",
"Forums powered by fifty five yellow herring",
"Forums powered by fifty six joyful cats",
"Forums powered by fifty six ugly penguins",
"Forums powered by fifty three green elves",
"Forums powered by fifty three grey moons",
"Forums powered by fifty three magenta candies",
"Forums powered by fifty three silly fish",
"Forums powered by fifty seven ugly elves",
"Forums powered by first posts",
"Forums powered by five cute dogs",
"Forums powered by floccinaucinihilipilification",
"Forums powered by forty eight green chickens",
"Forums powered by forty eight white midgets",
"Forums powered by forty five dumb moons",
"Forums powered by forty five grey cats",
"Forums powered by forty five nasty chickens",
"Forums powered by forty five orange geese",
"Forums powered by forty four black dogs",
"Forums powered by forty four happy cheesees",
"Forums powered by forty green geese",
"Forums powered by forty magenta dogs",
"Forums powered by forty one dumb penguins",
"Forums powered by forty red penguins",
"Forums powered by forty seven cyan herring",
"Forums powered by forty six sweet grunka-lunkas",
"Forums powered by forty six grey cats",
"Forums powered by forty three blue candies",
"Forums powered by forty three cyan penguins",
"Forums powered by fossil fuels",
"Forums powered by four hamsters in a wheel",
"Forums powered by four happy candies",
"Forums powered by fourteen happy chickens",
"Forums powered by fourteen grey butterflies",
"Forums powered by free horse manure",
"Forums powered by fresh air",
"Forums powered by government conspiracies",
"Forums powered by gravity",
"Forums powered by herring",
"Forums powered by halitosis",
"Forums powered by hot air",
"Forums powered by human stupidity",
"Forums powered by irrational arguments",
"Forums powered by less than fourteen bits",
"Forums powered by less than nineteen bits",
"Forums powered by less than seven bits",
"Forums powered by less than seventeen bits",
"Forums powered by luke-warm nuclear fusion",
"Forums powered by ME",
"Forums powered by midgets in grunka-lunka costumes",
"Forums powered by modulating the Warp core",
"Forums powered by navel lint",
"Forums powered by Never giving you up",
"Forums powered by Never letting you down",
"Forums powered by Never running around or deserting you",
"Forums powered by Never making you cry",
"Forums powered by Never saying goodbye",
"Forums powered by Never telling a lie or hurting you",
"Forums powered by ninety cyan candies",
"Forums powered by ninety four blue hamsters",
"Forums powered by ninety one ugly midgets",
"Forums powered by ninety one white dogs",
"Forums powered by ninety seven magenta fish",
"Forums powered by ninety seven silly herring ",
"Forums powered by ninety seven smart midgets",
"Forums powered by ninety three happy tyres",
"Forums powered by ninety two orange elves",
"Forums powered by ninety two ugly CD-ROMs",
"Forums powered by ninety seven green elves",
"Forums powered by nothing",
"Forums powered by one hundred ugly penguins",
"Forums powered by ones and zeros (and twos)",
"Forums powered by perpetual motion",
"Forums powered by pools of blue-green algae",
"Forums powered by powdered water",
"Forums powered by power itself",
"Forums powered by protons neutrons and electrons",
"Forums powered by public transport",
"Forums powered by QBASIC",
"Forums powered by recycled tyres",
"Forums powered by rubber bands",
"Forums powered by scooby snacks",
"Forums powered by seven cute dogs",
"Forums powered by seven penguins on bicycles",
"Forums powered by seventeen silly elves",
"Forums powered by seventeen different things",
"Forums powered by seventy four cute humans",
"Forums powered by seventy four nasty chickens",
"Forums powered by seventy four white elves",
"Forums powered by seventy three blue fish",
"Forums powered by seventy two dumb rubber bands",
"Forums powered by seventy six grey geese",
"Forums powered by six different things",
"Forums powered by six penguins on bicycles",
"Forums powered by six smart dogs",
"Forums powered by sixteen hamsters in a wheel",
"Forums powered by sixty eight cute midgets",
"Forums powered by sixty five red midgets",
"Forums powered by sixty four smart CD-ROMs",
"Forums powered by sixty four sweet humans",
"Forums powered by sixty nine cute humans",
"Forums powered by sixty nine dumb herring",
"Forums powered by sixty nine green herring",
"Forums powered by sixty nine silly midgets",
"Forums powered by sixty nine white butterflies",
"Forums powered by sixty one happy dogs",
"Forums powered by sixty orange moons",
"Forums powered by sleep deprivation",
"Forums powered by soy milk",
"Forums powered by spontaneous combustion",
"Forums powered by stale air",
"Forums powered by ten different things",
"Forums powered by ten joyful elves",
"Forums powered by ten lords a-leaping",
"Forums powered by The Department of Redundancy Department",
"Forums powered by the Emergency Medical Hologram",
"Forums powered by the force",
"Forums powered by the moons of Jupiter",
"Forums powered by thirteen blue elves",
"Forums powered by thirty eight green fish",
"Forums powered by thirty eight silly elves",
"Forums powered by thirty eight silly geese",
"Forums powered by thirty eight silly humans",
"Forums powered by thirty five cyan hamsters",
"Forums powered by thirty five happy hamsters",
"Forums powered by thirty four nasty dogs",
"Forums powered by thirty seven ugly herring",
"Forums powered by thirty seven yellow humans",
"Forums powered by thirty six cyan humans",
"Forums powered by thirty two sweet fish ",
"Forums powered by thirty one dumb moons",
"Forums powered by thirty two smart chickens",
"Forums powered by thirty two stupid geese",
"Forums powered by those little blue crunchy things!",
"Forums powered by three blind mice",
"Forums powered by three magenta penguins",
"Forums powered by three red butterflies",
"Forums powered by tinfoil hats",
"Forums powered by toenail clippings",
"Forums powered by twelve different things",
"Forums powered by twelve dumb chickens",
"Forums powered by twelve hamsters in a wheel",
"Forums powered by twelve stupid fish",
"Forums powered by twenty eight happy chickens",
"Forums powered by twenty eight stupid penguins",
"Forums powered by twenty four green cats ",
"Forums powered by twenty five smart humans",
"Forums powered by twenty green herring",
"Forums powered by twenty joyful cats",
"Forums powered by twenty nasty hamsters",
"Forums powered by twenty nine nasty midgets",
"Forums powered by twenty one dumb herring",
"Forums powered by twenty smart CD-ROMs",
"Forums powered by twenty two stupid hamsters",
"Forums powered by two blue penguins",
"Forums powered by two Little Green Men",
"Forums powered by two penguins on bicycles",
"Forums powered by underpaid sweatshop workers",
"Forums powered by vBullshit 2.1.4a",
"Forums powered by Windows 1.0",
"Forums powered by WebTV",
"Forums powered by your mind",
"Forums powered by three eskimos",
"Forums powered by nothing",
"Forums powered by Russian Mafia",
"Forums powered by free horse manure ",
"Forums powered by twenty four nasty chickens",
"Forums powered by ninety nine bottles of beer on the wall",
            ];